# Generated by Django 3.0.2 on 2020-02-01 14:41

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuneSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('quality', models.IntegerField(choices=[(1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend'), (11, 'Ancient Common'), (12, 'Ancient Magic'), (13, 'Ancient Rare'), (14, 'Ancient Hero'), (15, 'Ancient Legend')])),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('upgrade_curr', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('base_value', models.IntegerField()),
                ('sell_value', models.IntegerField()),
                ('primary', models.IntegerField(choices=[(1, 'HP flat'), (2, 'HP%'), (3, 'ATK flat'), (4, 'ATK%'), (5, 'DEF flat'), (6, 'DEF%'), (8, 'SPD'), (9, 'CRate'), (10, 'CDmg'), (11, 'RES'), (12, 'ACC')])),
                ('primary_value', models.IntegerField()),
                ('innate', models.IntegerField(choices=[(1, 'HP flat'), (2, 'HP%'), (3, 'ATK flat'), (4, 'ATK%'), (5, 'DEF flat'), (6, 'DEF%'), (8, 'SPD'), (9, 'CRate'), (10, 'CDmg'), (11, 'RES'), (12, 'ACC')])),
                ('innate_value', models.IntegerField()),
                ('substats', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'HP flat'), (2, 'HP%'), (3, 'ATK flat'), (4, 'ATK%'), (5, 'DEF flat'), (6, 'DEF%'), (8, 'SPD'), (9, 'CRate'), (10, 'CDmg'), (11, 'RES'), (12, 'ACC')]), size=None)),
                ('substats_values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('substats_grindstones', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('substats_enchants', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('quality_original', models.IntegerField(choices=[(1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend'), (11, 'Ancient Common'), (12, 'Ancient Magic'), (13, 'Ancient Rare'), (14, 'Ancient Hero'), (15, 'Ancient Legend')])),
                ('equipped', models.BooleanField()),
                ('rune_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.RuneSet')),
            ],
        ),
    ]
