# Generated by Django 3.0.3 on 2020-03-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_siegerecord_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionholerun',
            name='dungeon',
            field=models.IntegerField(choices=[(1101, 'Ellunia'), (1201, 'Fairy (Ellunia)'), (1202, 'Pixie (Ellunia)'), (2101, 'Karzhan'), (2202, 'Inugami (Karzhan)'), (2201, 'Warbear (Karzhan)'), (3101, 'Lumel'), (3201, 'Werewolf (Lumel)'), (3202, 'Martial Cat (Lumel)')], db_index=True),
        ),
    ]
