# Generated by Django 3.0.3 on 2020-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200317_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionholerun',
            name='monsters',
            field=models.ManyToManyField(db_index=True, related_name='dimhole_monsters', related_query_name='dimhole_monsters', to='website.Monster'),
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='monsters',
            field=models.ManyToManyField(db_index=True, related_name='dungeon_monsters', to='website.Monster'),
        ),
        migrations.AlterField(
            model_name='riftdungeonrun',
            name='monsters',
            field=models.ManyToManyField(db_index=True, related_name='rift_dungeon_monsters', to='website.Monster'),
        ),
    ]
