# Generated by Django 3.0.6 on 2020-06-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200403_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidDungeonRun',
            fields=[
                ('battle_key', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('stage', models.IntegerField()),
                ('win', models.BooleanField(blank=True, null=True)),
                ('clear_time', models.DurationField(blank=True, db_index=True, null=True)),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('leader', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_leader', to='website.Monster')),
                ('monster_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_fl_1', to='website.Monster')),
                ('monster_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_fl_2', to='website.Monster')),
                ('monster_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_fl_3', to='website.Monster')),
                ('monster_4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_fl_4', to='website.Monster')),
                ('monster_5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_bl_1', to='website.Monster')),
                ('monster_6', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_bl_2', to='website.Monster')),
                ('monster_7', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_bl_3', to='website.Monster')),
                ('monster_8', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raid_monster_bl_4', to='website.Monster')),
                ('wizard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Wizard')),
            ],
            options={
                'ordering': ['-stage', '-clear_time', '-win'],
            },
        ),
        migrations.DeleteModel(
            name='RaidBattleKey',
        ),
        migrations.RemoveField(
            model_name='riftdungeonrun',
            name='monsters',
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='leader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_leader', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_fl_1', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_fl_2', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_fl_3', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_fl_4', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_bl_1', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_6',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_bl_2', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_7',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_bl_3', to='website.Monster'),
        ),
        migrations.AddField(
            model_name='riftdungeonrun',
            name='monster_8',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rift_monster_bl_4', to='website.Monster'),
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='dungeon',
            field=models.IntegerField(choices=[(1001, 'Hall of Dark'), (2001, 'Hall of Fire'), (3001, 'Hall of Water'), (4001, 'Hall of Wind'), (5001, 'Hall of Magic'), (6001, 'Necropolis'), (7001, 'Hall of Light'), (8001, 'Giants Keep'), (9001, 'Dragons Lair')], db_index=True),
        ),
    ]
