# Generated by Django 3.0.6 on 2020-06-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200626_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizarditem',
            name='master_item',
        ),
        migrations.RemoveField(
            model_name='wizarditem',
            name='wizard',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='WizardItem',
        ),
    ]
