# Generated by Django 3.0.6 on 2020-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200629_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='loses',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='arena',
            name='wins',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
