# Generated by Django 3.0.6 on 2020-07-31 13:41

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200728_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='avg_eff_artifacts',
            field=models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='avg_eff_total',
            field=models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='dungeon',
            field=models.IntegerField(choices=[(1001, 'Hall of Dark'), (2001, 'Hall of Fire'), (3001, 'Hall of Water'), (4001, 'Hall of Wind'), (5001, 'Hall of Magic'), (6001, 'Necropolis'), (7001, 'Hall of Light'), (8001, 'Giants Keep'), (9001, 'Dragons Lair'), (9501, 'Steel Fortress'), (9502, 'Punishers Crypt')], db_index=True),
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('rtype', models.SmallIntegerField(choices=[(1, 'Attribute'), (2, 'Archetype')], db_index=True)),
                ('attribute', models.SmallIntegerField(blank=True, choices=[(1, 'Water'), (2, 'Fire'), (3, 'Wind'), (4, 'Light'), (5, 'Dark')], db_index=True, null=True)),
                ('archetype', models.SmallIntegerField(blank=True, choices=[(1, 'Attack'), (2, 'Defense'), (3, 'HP'), (4, 'Support')], db_index=True, null=True)),
                ('level', models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('primary', models.SmallIntegerField(choices=[(100, 'HP+'), (101, 'ATK+'), (102, 'DEF+')], db_index=True)),
                ('primary_value', models.IntegerField(db_index=True)),
                ('substats', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_index=True, null=True), size=None)),
                ('substats_values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, db_index=True, null=True), size=None)),
                ('quality', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend')], db_index=True)),
                ('quality_original', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend')], db_index=True)),
                ('efficiency', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('efficiency_max', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('equipped', models.BooleanField(db_index=True)),
                ('locked', models.BooleanField(db_index=True)),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Wizard')),
            ],
            options={
                'ordering': ['rtype', 'attribute', 'archetype', '-efficiency', '-quality_original'],
            },
        ),
        migrations.AddField(
            model_name='monster',
            name='artifacts',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='equipped_artifacts', related_query_name='equipped_artifacts', to='website.Artifact'),
        ),
    ]
