# Generated by Django 3.0.6 on 2020-08-01 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200731_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='substats_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, db_index=True, null=True), size=None),
        ),
    ]
