# Generated by Django 3.0.6 on 2020-08-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200801_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='equipped_rta',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='monster',
            name='artifacts_rta',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='equipped_artifacts_rta', related_query_name='equipped_artifacts_rta', to='website.Artifact'),
        ),
        migrations.AddField(
            model_name='monster',
            name='runes_rta',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='equipped_runes_rta', related_query_name='equipped_runes_rta', to='website.Rune'),
        ),
        migrations.AddField(
            model_name='rune',
            name='equipped_rta',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.DeleteModel(
            name='RuneRTA',
        ),
    ]
