# Generated by Django 3.0.6 on 2020-12-27 15:47

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200822_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='eff_hp_def_break',
        ),
        migrations.RemoveField(
            model_name='monsterbase',
            name='recommendation_text',
        ),
        migrations.RemoveField(
            model_name='monsterbase',
            name='recommendation_votes',
        ),
        migrations.RemoveField(
            model_name='riftdungeonrun',
            name='clear_time',
        ),
        migrations.RemoveField(
            model_name='riftdungeonrun',
            name='win',
        ),
        migrations.AlterField(
            model_name='arena',
            name='rank',
            field=models.IntegerField(choices=[(901, 'Beginner'), (1001, 'Challenger I'), (1002, 'Challenger II'), (1003, 'Challenger III'), (2001, 'Fighter I'), (2002, 'Fighter II'), (2003, 'Fighter III'), (3001, 'Conqueror I'), (3002, 'Conqueror II'), (3003, 'Conqueror III'), (4001, 'Guardian I'), (4002, 'Guardian II'), (4003, 'Guardian III'), (5001, 'Legend')]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='archetype',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Attack'), (2, 'Defense'), (3, 'HP'), (4, 'Support')], null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='attribute',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Water'), (2, 'Fire'), (3, 'Wind'), (4, 'Light'), (5, 'Dark')], null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='efficiency',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='efficiency_max',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='equipped',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='equipped_rta',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='level',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='locked',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='primary',
            field=models.SmallIntegerField(choices=[(100, 'HP+'), (101, 'ATK+'), (102, 'DEF+')]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='primary_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='quality',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend')]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='quality_original',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend')]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='rtype',
            field=models.SmallIntegerField(choices=[(1, 'Attribute'), (2, 'Archetype')]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='substats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='substats_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='monsters',
            field=models.ManyToManyField(related_name='monsters_in_deck', related_query_name='monsters_in_deck', to='website.Monster'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='place',
            field=models.IntegerField(choices=[(1, 'Arena'), (2, 'Guild War'), (3, 'Raid'), (4, 'Lab Normal'), (5, 'Lab Rescue'), (6, 'ToA'), (7, 'Lab Speed Limit'), (8, 'Lab Time Limit'), (9, 'Lab Cooldown'), (10, 'Lab Explode'), (11, 'Lab Boss')]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='team_runes_eff',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='dimensionholerun',
            name='clear_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimensionholerun',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dimensionholerun',
            name='dungeon',
            field=models.IntegerField(choices=[(1101, 'Ellunia'), (1201, 'Fairy (Ellunia)'), (1202, 'Pixie (Ellunia)'), (2101, 'Karzhan'), (2201, 'Warbear (Karzhan)'), (2202, 'Inugami (Karzhan)'), (2203, 'Griffon (Karzhan)'), (3101, 'Lumel'), (3201, 'Werewolf (Lumel)'), (3202, 'Martial Cat (Lumel)'), (3301, 'Predator (Lumel)'), (4101, 'Khalderun'), (4201, 'Howl (Khalderun)'), (4202, 'Grim Reaper (Khalderun)'), (4301, 'Predator (Khalderun)')]),
        ),
        migrations.AlterField(
            model_name='dimensionholerun',
            name='monsters',
            field=models.ManyToManyField(related_name='dimhole_monsters', related_query_name='dimhole_monsters', to='website.Monster'),
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='clear_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='dungeon',
            field=models.IntegerField(choices=[(8001, 'Giants Keep'), (9001, 'Dragons Lair'), (6001, 'Necropolis'), (9501, 'Steel Fortress'), (9502, 'Punishers Crypt'), (5001, 'Hall of Magic'), (2001, 'Hall of Fire'), (3001, 'Hall of Water'), (4001, 'Hall of Wind'), (7001, 'Hall of Light'), (1001, 'Hall of Dark')]),
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dungeonrun',
            name='monsters',
            field=models.ManyToManyField(related_name='dungeon_monsters', to='website.Monster'),
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='depth',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='letter',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='acc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='artifacts',
            field=models.ManyToManyField(blank=True, related_name='equipped_artifacts', related_query_name='equipped_artifacts', to='website.Artifact'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='artifacts_rta',
            field=models.ManyToManyField(blank=True, related_name='equipped_artifacts_rta', related_query_name='equipped_artifacts_rta', to='website.Artifact'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='avg_eff',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='avg_eff_artifacts',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='avg_eff_total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='crit_dmg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='crit_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='defense',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='eff_hp',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='level',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='res',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='runes',
            field=models.ManyToManyField(blank=True, related_name='equipped_runes', related_query_name='equipped_runes', to='website.Rune'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='runes_rta',
            field=models.ManyToManyField(blank=True, related_name='equipped_runes_rta', related_query_name='equipped_runes_rta', to='website.Rune'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='monster',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='stars',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='monsterbase',
            name='awaken',
            field=models.SmallIntegerField(choices=[(0, 'Unawakened'), (1, 'Awakened'), (2, '2A')]),
        ),
        migrations.AlterField(
            model_name='monsterbase',
            name='base_class',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='monsterbase',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='monsterbase',
            name='max_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='monsterbase',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monsterfamily',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='monsterfamily',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='monstersource',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='raiddungeonrun',
            name='battle_key',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='raiddungeonrun',
            name='clear_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raiddungeonrun',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raiddungeonrun',
            name='win',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='riftdungeonrun',
            name='battle_key',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='riftdungeonrun',
            name='clear_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'F'), (2, 'D'), (3, 'C'), (4, 'B-'), (5, 'B'), (6, 'B+'), (7, 'A-'), (8, 'A'), (9, 'A+'), (10, 'S'), (11, 'SS'), (12, 'SSS')], null=True),
        ),
        migrations.AlterField(
            model_name='riftdungeonrun',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riftdungeonrun',
            name='dmg_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='riftdungeonrun',
            name='dungeon',
            field=models.IntegerField(choices=[(1001, 'Ice Beast'), (2001, 'Fire Beast'), (3001, 'Wind Beast'), (4001, 'Light Beast'), (5001, 'Dark Beast')]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='efficiency',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='efficiency_max',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='equipped',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rune',
            name='equipped_rta',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rune',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='innate',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'HP+'), (2, 'HP%'), (3, 'ATK+'), (4, 'ATK%'), (5, 'DEF+'), (6, 'DEF%'), (8, 'SPD'), (9, 'CRATE%'), (10, 'CDMG%'), (11, 'RES%'), (12, 'ACC%')], null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='innate_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rune',
            name='locked',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rune',
            name='primary',
            field=models.SmallIntegerField(choices=[(1, 'HP+'), (2, 'HP%'), (3, 'ATK+'), (4, 'ATK%'), (5, 'DEF+'), (6, 'DEF%'), (8, 'SPD'), (9, 'CRATE%'), (10, 'CDMG%'), (11, 'RES%'), (12, 'ACC%')]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='primary_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rune',
            name='quality',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend'), (11, 'Ancient Common'), (12, 'Ancient Magic'), (13, 'Ancient Rare'), (14, 'Ancient Hero'), (15, 'Ancient Legend')]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='quality_original',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Common'), (2, 'Magic'), (3, 'Rare'), (4, 'Hero'), (5, 'Legend'), (11, 'Ancient Common'), (12, 'Ancient Magic'), (13, 'Ancient Rare'), (14, 'Ancient Hero'), (15, 'Ancient Legend')]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='slot',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='stars',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_acc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_atk',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_atk_flat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_crit_dmg',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_crit_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_def',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_def_flat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_hp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_hp_flat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_res',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='sub_speed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rune',
            name='upgrade_curr',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='runeset',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='runeset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='runeset',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='siegerecord',
            name='monsters',
            field=models.ManyToManyField(related_name='siege_defense_monsters', to='website.Monster'),
        ),
        migrations.AlterField(
            model_name='siegerecord',
            name='ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wizard',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wizardbuilding',
            name='level',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
